# Generated by Django 6.0.2 on 2026-08-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='ai_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='risk_score',
            field=models.IntegerField(default=0),
        ),
    ]
