# Generated by Django 6.0.2 on 2026-08-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_incidentreport_ai_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='sensitivity_level',
            field=models.CharField(choices=[('low', 'Low'), ('high', 'High - Protected Species/Location')], default='low', max_length=20),
        ),
    ]
