# Generated by Django 6.0.2 on 2026-08-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_incidentreport_sensitivity_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='ai_removal_advice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='category',
            field=models.CharField(choices=[('wildlife_crime', 'Wildlife Crime / Poaching'), ('human_wildlife_conflict', 'Human-Wildlife Conflict'), ('injured_animal', 'Injured Animal'), ('invasive_species', 'Invasive Species'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
