# Generated by Django 6.0.2 on 2026-08-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_incidentreport_ai_removal_advice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='category',
            field=models.CharField(choices=[('conflict', 'Human-Wildlife Conflict'), ('injured', 'Injured / Trapped Animal'), ('sighting', 'Wildlife Sighting'), ('illegal', 'Suspected Illegal Activity'), ('invasive', 'Invasive Species'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
