# Generated by Django 6.0.2 on 2026-08-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_incidentreport_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='ai_species',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
