# Generated by Django 6.0.2 on 2026-08-15 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0004_incidentreport_sensitivity_level'),
        ('response_units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOSAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_alerts', to='reports.incidentreport')),
                ('response_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_alerts', to='response_units.responseunit')),
            ],
        ),
    ]
